# Generated by Django 3.2.5 on 2021-09-02 00:50

import accounts.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210827_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='resumes',
            field=models.FileField(blank=True, null=True, upload_to=accounts.utils.resume_file_path, verbose_name='رزومه'),
        ),
    ]
