# Generated by Django 3.2.5 on 2021-09-08 20:13

import accounts.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_profile_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=accounts.utils.resume_file_path, verbose_name='رزومه'),
        ),
    ]
