# Generated by Django 3.2.5 on 2021-08-04 17:06

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_profile_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('edit_date', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('img', models.ImageField(upload_to='', verbose_name='عکس')),
                ('auther', models.ManyToManyField(related_name='posts', to='accounts.Profile', verbose_name='نویسنده')),
            ],
        ),
    ]
