# Generated by Django 3.2.5 on 2021-08-04 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='auther',
        ),
        migrations.RemoveField(
            model_name='post',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='edit_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='img',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
