# Generated by Django 3.2.5 on 2021-08-04 18:35

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210804_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='create_date',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
    ]
