# Generated by Django 3.2.5 on 2021-08-05 01:16

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='edit_date',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ ویرایش'),
        ),
    ]
