# Generated by Django 3.2.5 on 2021-08-05 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_edit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=50, null=True, verbose_name='عنوان'),
        ),
    ]
