# Generated by Django 3.2.5 on 2021-08-05 01:32

import blog.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(height_field=100, null=True, upload_to=blog.utils.post_image_path, verbose_name='عکس', width_field=100),
        ),
    ]
