# Generated by Django 3.2.5 on 2021-08-05 01:41

import blog.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_post_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(upload_to=blog.utils.post_image_path, verbose_name='عکس'),
        ),
    ]
