# Generated by Django 3.2.5 on 2021-08-05 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'در حال انتشار'), (2, 'عدم تایید'), (3, 'پیش نویس')], default=3, verbose_name='وضعیت'),
        ),
    ]
