# Generated by Django 3.2.5 on 2021-08-05 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_alter_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(1, 'علمی'), (2, 'آموزشی'), (3, 'خبری')], default=3, null=True, verbose_name='دسته بندی'),
        ),
    ]
