# Generated by Django 3.2.5 on 2021-08-27 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20210805_0247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-create_date'], 'verbose_name': 'دیدگاه', 'verbose_name_plural': 'دیدگاه ها'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['create_date'], 'verbose_name': 'پست', 'verbose_name_plural': 'پست ها'},
        ),
    ]
